spring:
  application:
    name: embedded-db
    description: embedded-db for development purpose.
  flyway:
    enabled: true
    dbMigrationPath: "/db/migration"

logging:
  level:
    root: INFO

spring.banner:
  location: "classpath:banner/banner.txt"
  image:
    location: "classpath:banner/postgreSql.png"

